In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle

In [2]:
#Loading the data set.
bbc = pd.read_csv('bbc_news.csv' , encoding='ISO-8859-1')

In [3]:
bbc = shuffle(bbc)
x = bbc['news'].tolist()
y = bbc['type_integer'].tolist()

In [4]:
# Creating the BOW model
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer()
bag = count.fit_transform(x).toarray()
bag.shape

(2225, 29421)

In [5]:
# TF-IDF
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer(use_idf = True,
                        norm = 'l2',
                        smooth_idf = True)

np.set_printoptions(precision = 2)
X_train_tfidf = tfidf_transformer.fit_transform(count.fit_transform(x))
X_train_tfidf = X_train_tfidf.toarray()
X_train_tfidf.shape

(2225, 29421)

In [6]:
# Machine Learning
# Training Naive Bayes (NB) classifier on training data.
### Naive Bayes Model

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.naive_bayes import GaussianNB

Gaussian= GaussianNB()
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
fold_accuracies = cross_val_score(Gaussian, X_train_tfidf, y, cv=kfold)
print("Cross-validation score:\n{}".format(fold_accuracies))
print("Average cross-validation score: {:.2f}".format(fold_accuracies.mean()))

Cross-validation score:
[0.94 0.91 0.96 0.91 0.89 0.92 0.91 0.96 0.87 0.95]
Average cross-validation score: 0.92


In [7]:
### Decision Tree

from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier

Decisiontree = DecisionTreeClassifier()
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
fold_accuracies = cross_val_score(Decisiontree, X_train_tfidf, y, cv=kfold)
print("Cross-validation score:\n{}".format(fold_accuracies))
print("Average cross-validation score: {:.2f}".format(fold_accuracies.mean()))

Cross-validation score:
[0.82 0.82 0.87 0.82 0.81 0.8  0.82 0.85 0.72 0.84]
Average cross-validation score: 0.82


In [8]:
### logistic Regression
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
fold_accuracies = cross_val_score(logreg, X_train_tfidf, y, cv=kfold)
print("Cross-validation score:\n{}".format(fold_accuracies))
print("Average cross-validation score: {:.2f}".format(fold_accuracies.mean()))

Cross-validation score:
[0.98 0.96 0.98 0.97 0.97 0.96 0.97 0.97 0.95 0.99]
Average cross-validation score: 0.97


In [9]:
# 2. Majority Vote Ensemble Algorithm

from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier


clf1_bbc = DecisionTreeClassifier()
clf2_bbc = GaussianNB()
clf3_bbc = LogisticRegression()
eclf1_bbc = VotingClassifier(estimators=[('dec', clf1_bbc), ('gnb', clf2_bbc),('log',clf3_bbc)], voting='soft')
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores_bbc = cross_val_score(eclf1_bbc, X_train_tfidf,y, cv=kfold)
print(scores_bbc.mean())

/home/nbuser/anaconda3_420/lib/python3.5/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/home/nbuser/anaconda3_420/lib/python3.5/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/nbuser/anaconda3_420/lib/python3.5/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/nbuser/anaconda3_420/lib/python3.5/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empt

0.9546055023633497


/home/nbuser/anaconda3_420/lib/python3.5/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [10]:
### 2biii Bagging ensemble

from sklearn.ensemble import BaggingClassifier

bagging = BaggingClassifier(clf1_bbc)
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(bagging, X_train_tfidf, y, cv=kfold)
scores.mean()

0.8750535288651881

In [11]:
### 2biii Bagging ensemble

from sklearn.ensemble import BaggingClassifier

bagging = BaggingClassifier(clf2_bbc)
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(bagging, X_train_tfidf, y, cv=kfold)
scores.mean()

0.9298953662182361

In [12]:
### 2biii Bagging ensemble

from sklearn.ensemble import BaggingClassifier

bagging = BaggingClassifier(clf3_bbc)
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(bagging, X_train_tfidf, y, cv=kfold)
scores.mean()

0.9698844584494809

In [13]:
### 2biii Bagging ensemble

from sklearn.ensemble import BaggingClassifier

bagging = BaggingClassifier(eclf1_bbc)
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(bagging, X_train_tfidf, y, cv=kfold)
scores.mean()

0.9626974508140428

In [14]:
# 2biv Adaboost algorithm

from sklearn.ensemble import AdaBoostClassifier

adabooster = AdaBoostClassifier(base_estimator=eclf1_bbc,n_estimators=50)
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(adabooster, X_train_tfidf, y, cv=kfold)
scores.mean()

0.8736839978992446