In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
#Loading the data set.
reviews = pd.read_csv('movie_reviews.csv' , encoding='ISO-8859-1')

In [3]:
from sklearn.utils import shuffle
reviews = shuffle(reviews)
x_reviews = reviews['reviews'].tolist()
y_reviews = reviews['sentiment_1'].tolist()

In [4]:
# Creating the BOW model
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer()
bag = count.fit_transform(x_reviews).toarray()
bag.shape

(2000, 39659)

In [5]:
# TF-IDF
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer(use_idf = True,
                        norm = 'l2',
                        smooth_idf = True)

np.set_printoptions(precision = 2)
X_tfidf_reviews = tfidf_transformer.fit_transform(count.fit_transform(x_reviews))
X_tfidf_reviews = X_tfidf_reviews.toarray()
X_tfidf_reviews.shape

(2000, 39659)

In [6]:
# Machine Learning
# Training Naive Bayes (NB) classifier on training data.
### Naive Bayes Model

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.naive_bayes import GaussianNB

Gaussian= GaussianNB()
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
fold_accuracies = cross_val_score(Gaussian, X_tfidf_reviews, y_reviews, cv=kfold)
print("Cross-validation score:\n{}".format(fold_accuracies))
print("Average cross-validation score: {:.2f}".format(fold_accuracies.mean()))

Cross-validation score:
[0.62 0.64 0.65 0.66 0.64 0.68 0.7  0.64 0.66 0.61]
Average cross-validation score: 0.65


In [7]:
### Decision Tree
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier

Decisiontree = DecisionTreeClassifier()
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
fold_accuracies = cross_val_score(Decisiontree, X_tfidf_reviews, y_reviews, cv=kfold)
print("Cross-validation score:\n{}".format(fold_accuracies))
print("Average cross-validation score: {:.2f}".format(fold_accuracies.mean()))

Cross-validation score:
[0.6  0.66 0.69 0.61 0.61 0.66 0.7  0.69 0.61 0.67]
Average cross-validation score: 0.65


In [8]:
### logistic Regression
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
fold_accuracies = cross_val_score(logreg, X_tfidf_reviews, y_reviews, cv=kfold)
print("Cross-validation score:\n{}".format(fold_accuracies))
print("Average cross-validation score: {:.2f}".format(fold_accuracies.mean()))

Cross-validation score:
[0.81 0.86 0.8  0.83 0.79 0.81 0.85 0.83 0.86 0.85]
Average cross-validation score: 0.83


In [9]:
# 2. Majority Vote Ensemble Algorithm

from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_val_score

clf1 = DecisionTreeClassifier()
clf2 = GaussianNB()
clf3 = LogisticRegression()
eclf1 = VotingClassifier(estimators=[('dec', clf1), ('gnb', clf2),('log',clf3)], voting='soft')
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(eclf1, X_tfidf_reviews,y_reviews, cv=kfold)
print(scores.mean())

/home/nbuser/anaconda3_420/lib/python3.5/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/home/nbuser/anaconda3_420/lib/python3.5/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/nbuser/anaconda3_420/lib/python3.5/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/home/nbuser/anaconda3_420/lib/python3.5/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empt

0.7755


/home/nbuser/anaconda3_420/lib/python3.5/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [10]:
### 2biii Bagging ensemble

from sklearn.ensemble import BaggingClassifier

bagging = BaggingClassifier(clf1)
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(bagging, X_tfidf_reviews,y_reviews, cv=kfold)
scores.mean()

0.715

In [11]:
### 2biii Bagging ensemble

from sklearn.ensemble import BaggingClassifier

bagging = BaggingClassifier(clf2)
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(bagging, X_tfidf_reviews,y_reviews, cv=kfold)
scores.mean()

0.6775

In [12]:
### 2biii Bagging ensemble

from sklearn.ensemble import BaggingClassifier

bagging = BaggingClassifier(clf3)
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(bagging, X_tfidf_reviews,y_reviews, cv=kfold)
scores.mean()

0.8234999999999999

In [13]:
### 2biii Bagging ensemble

from sklearn.ensemble import BaggingClassifier

bagging = BaggingClassifier(eclf1)
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(bagging, X_tfidf_reviews,y_reviews, cv=kfold)
scores.mean()

0.7660000000000001

In [14]:
# 2biv Adaboost algorithm

from sklearn.ensemble import AdaBoostClassifier

adabooster = AdaBoostClassifier(base_estimator=eclf1,n_estimators=50)
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(adabooster, X_tfidf_reviews, y_reviews, cv=kfold)
scores.mean()

0.6639999999999999